version: '3.8'

services:

  web:
    # Build the image from the Dockerfile in the current directory (.)
    build: .
    
    # Name the container
    container_name: AutoShare_Server
    
    ports:
      - "8000:8000"
      
    volumes:
      - ./app:/app
      
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload