version: '3.8'

services:

  web:
    # Build the image from the Dockerfile in the current directory (.)
    build: .
    
    # Name the container
    container_name: AutoShare_Server
    
    ports:
      - "8000:8000"
      
    volumes:
      - ./app:/app
      - ./secrets:/secrets:ro
      
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    environment:
      FIREBASE_CREDENTIAL_PATH: /secrets/firebase-service-account.json